# /etc/nginx/conf.d/10-proxy-params.conf

# Headers which are useful to set when using nginx
# as a reverse proxy

proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Proto $scheme;
